version: '3'

services:
  backend:
    container_name: rishat_test_project_backend
    build: backend/
    restart: unless-stopped
    volumes:
      - ./backend:/backend
      - media:/backend/media
      - static:/backend/static
    expose:
      - 8000
    env_file:
      - .env
    environment:
      - PYTHONPATH=/backend/app
    depends_on:
      - postgres
    networks:
      - main_network
    logging:
      driver: "json-file"
      options:
        max-size: "3gb"

  postgres:
    container_name: rishat_test_project_postgres
    command:
      - "postgres"
      - "-c"
      - "max_connections=500"
    image: postgres:18-alpine
    restart: unless-stopped
    volumes:
      - postgresql-data:/var/lib/postgresql
    expose:
      - 5432
    env_file:
      - .env
    networks:
      - main_network
    logging:
      driver: "json-file"
      options:
        max-size: "3gb"

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    restart: unless-stopped
    volumes:
      - ./nginx/conf/nginx.conf:/etc/nginx/conf.d/default.conf
      - media:/media/
      - static:/static/
    networks:
      - main_network
    logging:
      driver: "json-file"
      options:
        max-size: "3gb"

networks:
  main_network:
volumes:
  postgresql-data:
  media:
  static:
