# Generated by Django 6.0.4 on 2026-05-04 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_item_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='currency',
            field=models.CharField(choices=[('usd', 'USD'), ('rub', 'RUB')], default='usd', max_length=3),
        ),
    ]
